Avoid SNAT service-instance leakage
Under load SVC will process notification messages after the action on
the API.

Considering the events that trigger SNAT creation we should get:
1. logical-router create
2. logical-router update (gateway-set)
3. virtual-machine-interface create (interface-add)
4. logical-router update (triggered by linking vmi to logical-router)

When SVC gets the first message all 3 actions might have been done
on the API side so it will create the SNAT service-instance at step 1
because the LR has a VMI and a ref to the public network.

During the creation it needs to add route-tables to all virtual-networks
attached to the logical router. To get the virtual-network it looks
in its memory cache for the vmis of the router but at this point
the vmis are not in the cache because the 3. message has not been
processed yet. The creation will fail and leave the created SI in
the API in a stale state.

When processing the 2. message, it will fail the same and leave another
stale SI in the API.

When processing the 3. message, the VMI is added to the cache.

When processing the 4. message, the SI creation will succeed because the
VMI is now in the cache.

To overcome this situation we use .locate instead of .get to get the VMI
from the cache which will read the object from the API if not found
in the cache.

Traceback::

    05/24/2016 08:20:35 AM [contrail-svc-monitor]: __default__ [SYS_DEBUG]: SvcMonitorLog: Notification Message: {u'imid': u'contrail:logical-router:default-domain:COMPUTE-15-07-29_12h44m17-83feae74-35ef-11e5-9ffc-525400446ecf:Cloud-OOCaasRouter-utpycbvqah5s',
     u'obj_dict': {u'display_name': u'Cloud-OOCaasRouter-utpycbvqah5s',
                   u'fq_name': [u'default-domain',
                                u'COMPUTE-15-07-29_12h44m17-83feae74-35ef-11e5-9ffc-525400446ecf',
                                u'Cloud-OOCaasRouter-utpycbvqah5s'],
                   u'id_perms': {u'created': u'2016-05-24T08:20:16.452086',
                                 u'creator': None,
                                 u'description': None,
                                 u'enable': True,
                                 u'last_modified': u'2016-05-24T08:20:16.452086',
                                 u'permissions': {u'group': u'_member_',
                                                  u'group_access': 7,
                                                  u'other_access': 7,
                                                  u'owner': u'neutron',
                                                  u'owner_access': 7},
                                 u'user_visible': True,
                                 u'uuid': {u'uuid_lslong': 11683263654533357847L,
                                           u'uuid_mslong': 15712162882175518634L}},
                   u'parent_type': u'project',
                   u'uuid': u'da0cd0e5-0d26-47aa-a223-4a64a9b16117'},
     u'oper': u'CREATE',
     u'parent_imid': u'contrail:project:default-domain:COMPUTE-15-07-29_12h44m17-83feae74-35ef-11e5-9ffc-525400446ecf',
     u'request-id': u'req-c22a6712-a7bf-4767-b639-56caa32826e4',
     u'type': u'logical-router',
     u'uuid': u'da0cd0e5-0d26-47aa-a223-4a64a9b16117'}
    05/24/2016 08:20:35 AM [contrail-svc-monitor]: __default__ [SYS_INFO]: SvcMonitorLog: Creating network snat-si-left_snat_da0cd0e5-0d26-47aa-a223-4a64a9b16117_45af6834-e2bd-413c-abf1-8fd4957c93ca subnet 100.64.0.0/29
    05/24/2016 08:20:36 AM [contrail-svc-monitor]: __default__ [SYS_ERR]: SvcMonitorLog: <type 'exceptions.AttributeError'>
    Python 2.7.6: /usr/bin/python
    Tue May 24 08:20:36 2016

    A problem occurred in a Python script.  Here is the sequence of
    function calls leading up to the error, in the order they occurred.

     /usr/lib/python2.7/dist-packages/svc_monitor/svc_monitor.py in _vnc_subscribe_callback(self=<svc_monitor.svc_monitor.SvcMonitor object>, oper_info={u'imid': u'contrail:logical-router:default-domain:COMPUTE...ffc-525400446ecf:Cloud-OOCaasRouter-utpycbvqah5s', u'obj_dict': {u'display_name': u'Cloud-OOCaasRouter-utpycbvqah5s', u'fq_name': [u'default-domain', u'COMPUTE-15-07-29_12h44m17-83feae74-35ef-11e5-9ffc-525400446ecf', u'Cloud-OOCaasRouter-utpycbvqah5s'], u'id_perms': {u'created': u'2016-05-24T08:20:16.452086', u'creator': None, u'description': None, u'enable': True, u'last_modified': u'2016-05-24T08:20:16.452086', u'permissions': {u'group': u'_member_', u'group_access': 7, u'other_access': 7, u'owner': u'neutron', u'owner_access': 7}, u'user_visible': True, u'uuid': {u'uuid_lslong': 11683263654533357847L, u'uuid_mslong': 15712162882175518634L}}, u'parent_type': u'project', u'uuid': u'da0cd0e5-0d26-47aa-a223-4a64a9b16117'}, u'oper': u'CREATE', u'parent_imid': u'contrail:project:default-domain:COMPUTE-15-07-29_12h44m17-83feae74-35ef-11e5-9ffc-525400446ecf', u'request-id': u'req-c22a6712-a7bf-4767-b639-56caa32826e4', u'type': u'logical-router', u'uuid': u'da0cd0e5-0d26-47aa-a223-4a64a9b16117'})
      215         self._db_resync_done.wait()
      216         try:
      217             self._vnc_subscribe_actions(oper_info)
      218         except Exception:
      219             cgitb_error_log(self)
    self = <svc_monitor.svc_monitor.SvcMonitor object>
    self._vnc_subscribe_actions = <bound method SvcMonitor._vnc_subscribe_actions of <svc_monitor.svc_monitor.SvcMonitor object>>
    oper_info = {u'imid': u'contrail:logical-router:default-domain:COMPUTE...ffc-525400446ecf:Cloud-OOCaasRouter-utpycbvqah5s', u'obj_dict': {u'display_name': u'Cloud-OOCaasRouter-utpycbvqah5s', u'fq_name': [u'default-domain', u'COMPUTE-15-07-29_12h44m17-83feae74-35ef-11e5-9ffc-525400446ecf', u'Cloud-OOCaasRouter-utpycbvqah5s'], u'id_perms': {u'created': u'2016-05-24T08:20:16.452086', u'creator': None, u'description': None, u'enable': True, u'last_modified': u'2016-05-24T08:20:16.452086', u'permissions': {u'group': u'_member_', u'group_access': 7, u'other_access': 7, u'owner': u'neutron', u'owner_access': 7}, u'user_visible': True, u'uuid': {u'uuid_lslong': 11683263654533357847L, u'uuid_mslong': 15712162882175518634L}}, u'parent_type': u'project', u'uuid': u'da0cd0e5-0d26-47aa-a223-4a64a9b16117'}, u'oper': u'CREATE', u'parent_imid': u'contrail:project:default-domain:COMPUTE-15-07-29_12h44m17-83feae74-35ef-11e5-9ffc-525400446ecf', u'request-id': u'req-c22a6712-a7bf-4767-b639-56caa32826e4', u'type': u'logical-router', u'uuid': u'da0cd0e5-0d26-47aa-a223-4a64a9b16117'}

     /usr/lib/python2.7/dist-packages/svc_monitor/svc_monitor.py in _vnc_subscribe_actions(self=<svc_monitor.svc_monitor.SvcMonitor object>, oper_info={u'imid': u'contrail:logical-router:default-domain:COMPUTE...ffc-525400446ecf:Cloud-OOCaasRouter-utpycbvqah5s', u'obj_dict': {u'display_name': u'Cloud-OOCaasRouter-utpycbvqah5s', u'fq_name': [u'default-domain', u'COMPUTE-15-07-29_12h44m17-83feae74-35ef-11e5-9ffc-525400446ecf', u'Cloud-OOCaasRouter-utpycbvqah5s'], u'id_perms': {u'created': u'2016-05-24T08:20:16.452086', u'creator': None, u'description': None, u'enable': True, u'last_modified': u'2016-05-24T08:20:16.452086', u'permissions': {u'group': u'_member_', u'group_access': 7, u'other_access': 7, u'owner': u'neutron', u'owner_access': 7}, u'user_visible': True, u'uuid': {u'uuid_lslong': 11683263654533357847L, u'uuid_mslong': 15712162882175518634L}}, u'parent_type': u'project', u'uuid': u'da0cd0e5-0d26-47aa-a223-4a64a9b16117'}, u'oper': u'CREATE', u'parent_imid': u'contrail:project:default-domain:COMPUTE-15-07-29_12h44m17-83feae74-35ef-11e5-9ffc-525400446ecf', u'request-id': u'req-c22a6712-a7bf-4767-b639-56caa32826e4', u'type': u'logical-router', u'uuid': u'da0cd0e5-0d26-47aa-a223-4a64a9b16117'})
      321             lr = LogicalRouterSM.get(lr_id)
      322             if lr:
      323                 self.snat_agent.update_snat_instance(lr)
      324
      325     def post_init(self, vnc_lib, args=None):
    self = <svc_monitor.svc_monitor.SvcMonitor object>
    self.snat_agent = <svc_monitor.snat_agent.SNATAgent object>
    self.snat_agent.update_snat_instance = <bound method SNATAgent.update_snat_instance of <svc_monitor.snat_agent.SNATAgent object>>
    lr = <svc_monitor.config_db.LogicalRouterSM object>

     /usr/lib/python2.7/dist-packages/svc_monitor/snat_agent.py in update_snat_instance(self=<svc_monitor.snat_agent.SNATAgent object>, router_obj=<svc_monitor.config_db.LogicalRouterSM object>)
       60             router_obj.virtual_machine_interfaces):
       61             if router_obj.service_instance is None:
       62                 self._add_snat_instance(router_obj)
       63             else:
       64                 self._update_snat_instance(router_obj)
    self = <svc_monitor.snat_agent.SNATAgent object>
    self._add_snat_instance = <bound method SNATAgent._add_snat_instance of <svc_monitor.snat_agent.SNATAgent object>>
    router_obj = <svc_monitor.config_db.LogicalRouterSM object>

     /usr/lib/python2.7/dist-packages/svc_monitor/snat_agent.py in _add_snat_instance(self=<svc_monitor.snat_agent.SNATAgent object>, router_obj=<svc_monitor.config_db.LogicalRouterSM object>)
      226         # Associate route table to all private networks connected onto
      227         # that router
      228         net_uuids = self._get_net_uuids(router_obj.virtual_machine_interfaces)
      229         self._add_route_tables(net_uuids, rt_obj)
      230
    net_uuids undefined
    self = <svc_monitor.snat_agent.SNATAgent object>
    self._get_net_uuids = <bound method SNATAgent._get_net_uuids of <svc_monitor.snat_agent.SNATAgent object>>
    router_obj = <svc_monitor.config_db.LogicalRouterSM object>
    router_obj.virtual_machine_interfaces = set(['717c73cb-f2ce-4e51-9f15-9731cab73616'])

     /usr/lib/python2.7/dist-packages/svc_monitor/snat_agent.py in _get_net_uuids(self=<svc_monitor.snat_agent.SNATAgent object>, vmi_uuids=set(['717c73cb-f2ce-4e51-9f15-9731cab73616']))
       84          return [
       85              VirtualMachineInterfaceSM.get(uuid).virtual_network
       86              for uuid in vmi_uuids]
       87
       88     def _virtual_network_read(self, net_uuid):
    uuid = '717c73cb-f2ce-4e51-9f15-9731cab73616'
    vmi_uuids = set(['717c73cb-f2ce-4e51-9f15-9731cab73616'])
    <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'virtual_network'
        __class__ = <type 'exceptions.AttributeError'>
        __delattr__ = <method-wrapper '__delattr__' of exceptions.AttributeError object>
        __dict__ = {}
        __doc__ = 'Attribute not found.'
        __format__ = <built-in method __format__ of exceptions.AttributeError object>
        __getattribute__ = <method-wrapper '__getattribute__' of exceptions.AttributeError object>
        __getitem__ = <method-wrapper '__getitem__' of exceptions.AttributeError object>
        __getslice__ = <method-wrapper '__getslice__' of exceptions.AttributeError object>
        __hash__ = <method-wrapper '__hash__' of exceptions.AttributeError object>
        __init__ = <method-wrapper '__init__' of exceptions.AttributeError object>
        __new__ = <built-in method __new__ of type object>
        __reduce__ = <built-in method __reduce__ of exceptions.AttributeError object>
        __reduce_ex__ = <built-in method __reduce_ex__ of exceptions.AttributeError object>
        __repr__ = <method-wrapper '__repr__' of exceptions.AttributeError object>
        __setattr__ = <method-wrapper '__setattr__' of exceptions.AttributeError object>
        __setstate__ = <built-in method __setstate__ of exceptions.AttributeError object>
        __sizeof__ = <built-in method __sizeof__ of exceptions.AttributeError object>
        __str__ = <method-wrapper '__str__' of exceptions.AttributeError object>
        __subclasshook__ = <built-in method __subclasshook__ of type object>
        __unicode__ = <built-in method __unicode__ of exceptions.AttributeError object>
        args = ("'NoneType' object has no attribute 'virtual_network'",)
        message = "'NoneType' object has no attribute 'virtual_network'"

    The above is a description of an error in a Python program.  Here is
    the original traceback:

    Traceback (most recent call last):
      File "/usr/lib/python2.7/dist-packages/svc_monitor/svc_monitor.py", line 217, in _vnc_subscribe_callback
        self._vnc_subscribe_actions(oper_info)
      File "/usr/lib/python2.7/dist-packages/svc_monitor/svc_monitor.py", line 323, in _vnc_subscribe_actions
        self.snat_agent.update_snat_instance(lr)
      File "/usr/lib/python2.7/dist-packages/svc_monitor/snat_agent.py", line 62, in update_snat_instance
        self._add_snat_instance(router_obj)
      File "/usr/lib/python2.7/dist-packages/svc_monitor/snat_agent.py", line 228, in _add_snat_instance
        net_uuids = self._get_net_uuids(router_obj.virtual_machine_interfaces)
      File "/usr/lib/python2.7/dist-packages/svc_monitor/snat_agent.py", line 86, in _get_net_uuids
        for uuid in vmi_uuids]
    AttributeError: 'NoneType' object has no attribute 'virtual_network'

Change-Id: Id870475af8a0a3f4241fc1132dca686d95d49aea